### ISSUE TITLE
Verify command doesn't works

### ISSUE THREAD

**Issue by viveksahu26** [rewanthtammana/sigstore-the-easy-way#11]
[Here](https://rewanthtammana.com/sigstore-the-easy-way/cosign/sign-and-verify-without-key/), under the section of `Verify the artifact
`, the command `cosign verify $IMAGE`  throws an error:
```
cosign verify $IMAGE                                                                                                      1 ↵ ──(Wed,Jul26)─┘

Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
```

Actual behaviour:  throw an error.
Desired Behaviour: shouldn't throw an error. Or there would be some changes in the upstream project which requires values `--certificate-identity` along with the `cosign verify` command.

**Comment by rewanthtammana** [comment]
@viveksahu26 In the docs, its mentioned, `COSIGN_EXPERIMENTAL=1  cosign verify $IMAGE`. Did you try with this environment variable?
