### ISSUE TITLE
command is incorrect

### ISSUE THREAD

**Issue by viveksahu26** [rewanthtammana/sigstore-the-easy-way#12]
[Here](https://rewanthtammana.com/sigstore-the-easy-way/cosign/attest-and-verify-artifacts/) , under the `Extract artifact from the registry` section:
the command `cosign verify-attestation --key cosign.pub $IMAGE | jq -r .payload | base64 -D | jq .` is incorrect. 

On running it, return an error:  `base64: invalid option -- 'D'` 
Instead it should be `-d` in place of `-D`.
Therefore the whole correct command would be:
`cosign verify-attestation --key cosign.pub $IMAGE | jq -r .payload | base64 -d | jq .`

**Comment by rewanthtammana** [comment]
Looks like its a mac thing but sure will fix it over.
![image](https://github.com/rewanthtammana/sigstore-the-easy-way/assets/22347290/92b0eebc-1978-4f91-afaa-6806a86b738e)
