### ISSUE TITLE
docs: missing sbom in demo

### ISSUE THREAD

**Issue by denhamparry** [rewanthtammana/sigstore-the-easy-way#2]
There is a missing `sbom` within the [cosign/attach-artifacts](https://rewanthtammana.com/sigstore-the-easy-way/cosign/attach-artifacts/) document.

Currently:

```bash
cosign attach --sbom image.sbom $IMAGE
```

Should be:

```bash
cosign attach sbom --sbom image.sbom $IMAGE
```

Thank you for creating this workshop 🙌

**Comment by rewanthtammana** [comment]
Thanks for highlighting it, @denhamparry. Fixed it 😁
